resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/2023-1.1
      endpoint: github

jobs:
  - template: 2023-1.1-py39.yml@templates
    parameters:
      beamline_acronym: TES
  - template: 2023-1.1-py310.yml@templates
    parameters:
      beamline_acronym: TES
  - template: 2023-1.1-py39-tiled.yml@templates
    parameters:
      beamline_acronym: TES
  - template: 2023-1.1-py310-tiled.yml@templates
    parameters:
      beamline_acronym: TES
